describe('order process', () => {
  it('order', () => {
    cy.viewport(1920, 1080)
    cy.visit('https://www.walcart.com/')
    cy.get("#search").type("Monitor")
    cy.get("button.action.search").click()
    cy.get("a.product-item-link").contains("Walton Monitor 21.45 Inch LED WD215V04").click()
    cy.wait(4000)
    cy.get("select#attribute93").select('কালো').should("have.value", "5")
    cy.get("button#product-addtocart-button").click()
    cy.get("button.cart-btn-qty.plus").click()
    cy.get("button.update-cart-item").contains("Update").click()
    cy.get("button.action.primary.checkout").click()
    cy.get("#mobile").type("01303117693")
    cy.get("button.action.primary.mobile-login-button").click()
    cy.get("#pass").type("Ullas199520")
    cy.get("button.action.primary.mobile-login-code-button").click()
    cy.xpath("//a[@title='Go to Home Page']").click()
    cy.get("a[href='https://www.walcart.com/daily-deals.html']").click()
    cy.xpath("//a[@title='Walton 10 Inch E-Writing Pad MYS3']").click() 
    cy.wait(4000)
    cy.get("#product-addtocart-button").click()
    cy.wait(4000)
    cy.xpath(`//*[@id="top-cart-btn-checkout"]`).click()
  })
})
